"use client";
import { useContext, useEffect, useState } from "react";
import TodoList from "./TodoList";
import TodoInput from "./TodoInput";
import Header from "./Header/Header";
import { TodoContext } from "@/app/_utils/contexts/TodoContext";
import CompletedList from "./CompletedList";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Todo() {
  const { todo } = useContext(TodoContext);

  const notCompletedTodo = todo.filter((list: any) => !list.status);
  const completedTodo = todo.filter((list: any) => list.status);
  return (
    <div className="overflow-y-auto flex-4 flex gap-3 flex-col bg-linear-45 from-purple-300 to-rose-400 h-screen p-15">
      <Header />
      <TodoInput />
      <TodoList todo={notCompletedTodo} />
      {completedTodo.length > 0 && <CompletedList todo={completedTodo} />}
      <div>
        <div draggable={true}>Box1</div>
        <div draggable={true}>Box2</div>
      </div>
    </div>
  );
}
