import type { Metadata } from "next";
import "./globals.css";
import { dana, iranSansX, TodoProvider } from "./_utils";

export const metadata: Metadata = {
  title: "Niki Portfolio",
  description: "Generated by Nikiabed",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = "fa";
  return (
    <html lang={locale} dir="rtl">
      <body className={dana.className}>
        <main className={`min-h-screen overflow-y-auto`}>
          <TodoProvider>{children}</TodoProvider>
        </main>
      </body>
    </html>
  );
}
