import type { Metadata } from "next";
import "./globals.css";
import { dana, ThemeProvider, TodoProvider } from "./_utils";
import { SessionProvider } from "next-auth/react";
import { FeedbackProvider } from "./feedback";

export const metadata: Metadata = {
  title: "Niki Portfolio",
  description: "Generated by Nikiabed",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = "fa";
  return (
    <html lang={locale} dir="rtl">
      <body className={dana.className}>
        <ThemeProvider>
          <SessionProvider>
            <FeedbackProvider>
              <TodoProvider>
                <main className="min-h-screen overflow-y-auto">{children}</main>
              </TodoProvider>
            </FeedbackProvider>
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
