import type { Metadata } from "next";
import "./globals.css";
import { iranSansX } from "./_utils/constants";
import { TodoProvider } from "./_utils/contexts/TodoContext";

export const metadata: Metadata = {
  title: "Niki Portfolio",
  description: "Generated by Nikiabed",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = 'fa'
  return (
    <html lang={locale} dir="rtl">
      <body>
        <main className={`min-h-screen overflow-y-auto ${iranSansX.className}`}>
          <TodoProvider>{children}</TodoProvider>
        </main>
      </body>
    </html>
  );
}
