import { Metadata } from "next";
import { Sidebar, Todo } from "./_common";

export const metadata: Metadata = {
  title: "Todo App",
  description: "Generated by Niki Abedzade",
};

export default function todoPage() {

  return (
    <div className="h-screen w-full flex ">
      <Sidebar />
      <Todo />
    </div>
  );
}
