import { Metadata } from "next";
import { Sidebar, Todo } from "./_common";
import { auth } from "@/app/lib/auth";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Todo App",
  description: "Generated by Niki Abedzade",
};

export default async function todoPage() {
  const session = await auth();

  if (!session) {
    redirect("/login");
  }

  return (
    <div className="h-screen w-full flex ">
      <Sidebar />
      <Todo />
    </div>
  );
}
