import { Metadata } from "next";
import { auth } from "@/app/lib/auth";
import { redirect } from "next/navigation";
import TodoLayout from "./_common/Todo/TodoLayout";

export const metadata: Metadata = {
  title: "Todo App",
  description: "Generated by Niki Abedzade",
};

export default async function todoPage() {
  const session = await auth();

  if (!session) {
    redirect("/login");
  }

  return <TodoLayout />;
}
